export const displayClassname = 'show';
export const messageBaseClassname = 'message';
export const selfMessageClassname = 'message--self';
export const recievedMessageClassname = 'message--received';
export const messageAuthorClassname = 'message__author';
export const messageContentClassname = 'message__content';
export const chatbotMessageContentClassname = 'message__content--chatbot';
export const chatbotJoinMessageCore = 'has joined the conversation!';
export const chatbotLeaveMessageCore = 'has left the conversation :('
export const minUsernameLength = 3;
export const API_URL = 'http://localhost:8000/api'